config/routes.rb
Rails.application.routes.draw do
  resource :registrations, only: %i[create new]
  resource :session
  resources :passwords, param: :token
  resources :profiles, only: [ :show ] do
    collection do
      post :search
    end
  end
  resources :following_users, only: :create
  resources :posts do
    resources :post_comments
    member do
      get :like
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session, :user
  delegate :user, to: :session, allow_nil: true
end

app/models/following_user.rb
class FollowingUser < ApplicationRecord
  belongs_to :user
  belongs_to :following_user, class_name: "User"

  after_commit do
    broadcast_update_to(:suggestions, target: "suggestions_user_#{user_id}", partial: "components/suggestions_for_current_user", locals: {current_user: user})
    broadcast_update_to(:suggestions, target: "stories_user_#{user_id}", partial: "components/stories_for_current_user", locals: {current_user: user})
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments

  def likes_count!
    self.likes_count = self.likes_count+1
    update_column(:likes_count, self.likes_count)
    broadcast_update(target: "count_of_#{id}", html: self.likes_count)
    broadcast_update_to(:suggestions, target: "total_of_likes_user_#{user_id}", html: user.posts_likes_count)
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_commit :broadcast_post_comments

  def broadcast_post_comments
    broadcast_update_to("post_comments", target: "post_comments_of_#{post_id}", partial: "components/post_comments", locals: {post: post})
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  validates :email_address, presence: true, uniqueness: true
  validates :password, confirmation: true, presence: true, length: {minimum: 6}
  belongs_to :company

  has_many :posts
  has_many :following_users

  def rememberable?
    self.remember_me
  end

  def suggestion_users
    User.where.not(id: id).where.not(id: following_users.pluck(:following_user_id))
  end

  def users
    User.where.not(id: id).where(id: following_users.pluck(:following_user_id))
  end

  def posts_likes_count
    posts.sum(:likes_count)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?, :current_user
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      Current.session.present?
    end

    def current_user
      @current_user ||= Current.user
    end

    def require_authentication
      resume_session || request_authentication
    end


    def resume_session
      Current.session = find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id])
    end


    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_url
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end


    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = {value: session.id, httponly: true, same_site: :lax}
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/following_users_controller.rb
class FollowingUsersController < ApplicationController
  def create
    current_user.following_users.create!(fowllowing_users_params)

    head :ok
  end

  private
    def fowllowing_users_params
      params.require(:following_user).permit(:following_user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Current.user.posts.order(created_at: :desc)
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  before_action :set_post

  def create
    @post_comment = @post.post_comments.build(post_comment_params.merge(user: current_user))
    @post_comment.save
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

    def set_post
      @post = Post.find(params[:post_id])
    end

    def post_comment_params
      params.require(:post_comment).permit(:comment)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: :like
  def like
    @post.likes_count!
    head :ok
  end

  private
    def set_post
      @post ||= Post.find(params[:id])
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: :show

  def search
    @users = params[:query].present? ? User.where("username LIKE ?", "%#{params[:query]}%").order(:username) : []
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def show
    @posts = @user.posts.order(created_at: :desc)
    render "home/index"
  end

  protected

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_url, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/following_users_helper.rb
module FollowingUsersHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def suggestion
    {
      avatar: Faker::Avatar.image,
      address: Faker::Address.full_address,
      company_name: Faker::Company.name,
      dob: Time.now,
      email: Faker::Internet.email,
      id: rand(100),
      name: Faker::Name.first_name,
      phone: Faker::PhoneNumber.cell_phone_with_country_code,
      username: Faker::Internet.username,
      website: Faker::Internet.url
    }
  end

  def post
    {
      id: rand(10000),
      username: Faker::Internet.username,
      user_image: Faker::Avatar.image,
      image: Faker::LoremFlickr.image,
      caption: "Subscribe now!"
    }
  end
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/index.html.erb
<div class="shadow-sm border-b bg-black text-white sticky top-0 z-50 pb-2 pt-2"><%= render "components/header" %></div>
<main id="feed" class="grid grid-cols-1 md:grid-cols-2 md:max-w-3xl xl:grid-cols-3 xl:max-w-6xl mx-auto">
  <%= render "components/left_side" %>
  <%= render "components/right_side" %>
</main>
<div id="modal"></div>

app/views/post_comments/_form.html.erb
<%= form_with model: [post, PostComment.new], class: "flex items-center p-4" do |f| %>
  <%= heroicon "face-smile", class: "h-7" %>
  <%= f.text_field :comment, required: true, placeholder: "Add comment", class: "flex-1 outline-none mx-2 rounded-md focus:ring-transparent focus:border-solid focus:border-[#363636] bg-black border-[#363636] border-1" %>
  <%= f.submit "Post", class: "font-semibold text-blue-400" %>
<% end %>

app/views/post_comments/create.turbo_stream.erb
<%= turbo_stream.replace "post_comment_form_#{@post_comment.post_id}" do %>
  <%= render partial: "post_comments/form", locals: { post: @post_comment.post } %>
<% end %>

app/views/posts/_post.html.erb
<div class="bg-black text-white my-7 border rounded-sm">
  <div class="flex items-center p-5">
    <%= image_tag post.user.avatar, class: "rounded-full w-12 h-12 object-contain border p-1 mr-3" %>
    <p class="flex-1 font-bold"><%= post.user.username %></p>
  </div>

  <%= image_tag post.image, class: "object-cover w-full" %>

  <div class="flex justify-between px-4 pt-4">
    <div class="flex space-x-4">
      <div class="relative">
        <%= turbo_stream_from post %>
          <%= turbo_frame_tag dom_id(post, :like_button) do %>
            <%= link_to like_post_path(post), method: :post, remote: true, class: "relative" do %>
              <%= heroicon("heart", options: { class: "h-7 hover:scale-125 transition-all duration-150 ease-out" }) %>
              <div id="count_of_<%= post.id %>" class="absolute -top-1 -right-2 text-xs w-5 h-5 bg-red-500 rounded-full flex items-center justify-center animate-pulse text-white">
                <%= post.likes_count %>
              </div>
            <% end %>
          <% end %>
      </div>
      <%= heroicon "chat-bubble-bottom-center", class: "h-7 hover:scale-125 cursor-pointer transition-all duration-150 ease-out" %>
      <%= heroicon "paper-airplane", class: "h-7 hover:scale-125 cursor-pointer transition-all duration-150 ease-out" %>
    </div>
    <%= heroicon "bookmark", class: "h-7 hover:scale-125 cursor-pointer transition-all duration-150 ease-out" %>
  </div>

  <p class="p-5 truncate">
    <span class="font-bold mr-1"><%= post.user.username %> </span><%= post.caption %>
  </p>

  <%= turbo_stream_from "post_comments" %>
  <div id="post_comments_of_<%= post.id %>">
    <%= render partial: "components/post_comments", locals: { post: post } %>
  </div>

  <%= turbo_frame_tag post_post_comments_path(post) do %>
    <div id="post_comment_form_<%= post.id %>"><%= render partial: "post_comments/form", locals: { post: post } %></div>
  <% end %>
</div>

app/views/profiles/_results.html.erb
<% if @users.present? %>
<div class="absolute -ml-[60px] m-5 border mt-4 w-[350px] bg-black text-white">
  <div class="w-auto">
    <div class="flex justify-center -mt-[16px]">
      <%= heroicon "chevron-up", class: "stroke-gray-200 fill-white flex-no-shrink h-[25px]" %>
    </div>
  </div>
  <div class="flex justify-end">
    <div data-controller="profiles" class="m-2">
      <%= heroicon "x-circle", class: "cursor-pointer", data: { action: "click->profiles#close" } %>
    </div>
  </div>
  <ul class="max-h-[250px] overflow-y-auto">
    <% @users.each do |user| %>
      <li class="m-5">
        <div class="flex items-center justify-between mt-3">
          <%= link_to image_tag(user.avatar, class: "w-10 h-10 rounded-full border p-[2px]"), profile_path(user), class: "inline-block", "data-turbo-frame": "_top" %>
          <div class="flex-1 ml-4 ">
            <h2 class="font-semibold text-sm"><%= user.username %></h2>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/profiles/search.html.erb
<%= render "profiles/results" %>

app/views/profiles/search.turbo_stream.erb
<%= turbo_stream.update "results", partial: "profiles/results" %>